spring.application.name=high-performance-url-shortener
spring.profiles.active=local
api.security.token.secret=${TOKEN}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Logging padrao
logging.level.root=info

# Server
server.port=8080
server.address=0.0.0.0
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Jackson (Datas)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.visibility.field=any

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google Auth
google.client.id=${GOOGLE_ID}

# Cors

